basePath: /
definitions:
  DTO.FatsecretMeal:
    properties:
      calories:
        type: number
      carbs:
        type: number
      fat:
        type: number
      foodDescription:
        type: string
      foodID:
        type: integer
      foodName:
        type: string
      portion:
        type: string
      protein:
        type: number
    type: object
  DTO.FindResponse:
    properties:
      findResponse:
        items:
          $ref: '#/definitions/DTO.FatsecretMeal'
        type: array
    type: object
  DTO.ProfileResponse:
    properties:
      email:
        type: string
      name:
        type: string
      surName:
        type: string
      userID:
        type: integer
      username:
        type: string
    type: object
  DTO.RationHistory:
    properties:
      objects:
        items:
          $ref: '#/definitions/models.DailyRation'
        type: array
    type: object
  DTO.UpdateEmailRequest:
    properties:
      new_email:
        type: string
    type: object
  DTO.UpdateNameRequest:
    properties:
      new_name:
        type: string
    type: object
  DTO.UpdatePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  DTO.UpdateUsernameRequest:
    properties:
      new_username:
        type: string
    type: object
  handlers.LoginData:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.DailyRation:
    properties:
      createdAt:
        type: string
      dailyRationID:
        type: integer
      ration:
        type: string
      userID:
        type: integer
    type: object
  models.User:
    properties:
      dailyRation:
        items:
          $ref: '#/definitions/models.DailyRation'
        type: array
      email:
        type: string
      name:
        type: string
      password:
        type: string
      surName:
        type: string
      userCharacteristics:
        items:
          $ref: '#/definitions/models.UserCharacteristics'
        type: array
      userID:
        type: integer
      username:
        type: string
    type: object
  models.UserCharacteristics:
    properties:
      createdAt:
        type: string
      endurance:
        type: string
      flexibility:
        type: string
      height:
        type: string
      imt:
        type: string
      lowerStr:
        type: string
      ration:
        type: string
      userCharacteristicsID:
        type: integer
      userID:
        type: integer
      weight:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample auth service API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Auth Service API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user by verifying their username and password, and
        return a JWT if successful
      parameters:
      - description: User login credentials
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginData'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "401":
          description: Invalid login or password
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Authenticate a user and issue a JWT
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the given details, including hashing the
        password before saving to the database
      parameters:
      - description: User registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            type: string
      summary: Register a new user
      tags:
      - Auth
  /search-food:
    get:
      consumes:
      - application/json
      description: Запрашивает данные о пище с API и возвращает информацию в формате
        JSON
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/DTO.FindResponse'
        "500":
          description: error message
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить информацию о пище
      tags:
      - Ration
  /user/add-meal:
    post:
      consumes:
      - application/json
      description: Create a new meal using the provided data and associate it with
        the authenticated user based on JWT claims.
      parameters:
      - description: Ration details
        in: body
        name: ration
        required: true
        schema:
          $ref: '#/definitions/models.DailyRation'
      produces:
      - application/json
      responses:
        "201":
          description: Meal add successfully
          schema:
            $ref: '#/definitions/models.DailyRation'
        "400":
          description: Invalid request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create a new meal and associate it with the current user
      tags:
      - Ration
  /user/profile:
    get:
      consumes:
      - application/json
      description: Retrieves the profile of the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/DTO.ProfileResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - User
  /user/ration-history:
    get:
      consumes:
      - application/json
      description: Retrieves the ration history of the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: User ration history retrieved successfully
          schema:
            $ref: '#/definitions/DTO.RationHistory'
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - Ration
  /user/targets:
    delete:
      consumes:
      - application/json
      description: Delete the meal if it is associated with the authenticated user
        based on JWT claims.
      parameters:
      - description: Daily ration ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Meal deleted successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Target not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete a meal associated with the current user
      tags:
      - Ration
  /user/update-email:
    put:
      consumes:
      - application/json
      description: Allows an authenticated user to update their email address
      parameters:
      - description: Update email request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdateEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email updated successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update user email
      tags:
      - User
  /user/update-name:
    put:
      consumes:
      - application/json
      description: Allows an authenticated user to update their name
      parameters:
      - description: Update name request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdateNameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Name updated successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update name
      tags:
      - User
  /user/update-password:
    put:
      consumes:
      - application/json
      description: Allows an authenticated user to update their password by providing
        the old password and a new password
      parameters:
      - description: Update password request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password updated successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "401":
          description: Invalid old password
          schema:
            type: string
        "403":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update user password
      tags:
      - User
  /user/update-username:
    put:
      consumes:
      - application/json
      description: Allows an authenticated user to update their username. It also
        checks if the new username is already taken.
      parameters:
      - description: Update username request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdateUsernameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Username updated successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "409":
          description: Username already taken
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update user username
      tags:
      - User
swagger: "2.0"
